apiVersion: apps/v1
kind: Deployment
metadata:
  name: foxmini-frontend
  namespace: foxmini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foxmini-frontend
  template:
    metadata:
      labels:
        app: foxmini-frontend
    spec:
      containers:
      - name: foxmini-frontend
        image: fengjy209/foxmini-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foxmini-frontend
  namespace: foxmini-app
spec:
  selector:
    app: foxmini-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort