apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
data:
  # 使用 base64 编码的密码: echo -n "yourpassword" | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-database: Zm94bWluaV9kYg==    # foxmini_db
  mysql-username: YXBwX3VzZXI=            # app_user
  mysql-password: dXNlcnBhc3N3b3Jk        # userpassword